server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: /Users/mundane/develop/temp/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    tradeType: NATIVE
    spbillCreateIp: 127.0.0.1
    notifyUrl: http://ueizdi.natappfree.cc/wxpay/notify
