server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    fetch-registry: false #不用拉取服务
    register-with-eureka: false #不用在eureka中注册自己
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka