server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.122
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.1.122
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15


mybatis:
  type-aliases-package: com.leyou.user.pojo
